apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sata-local-path
provisioner: rancher.io/local-path
parameters:
  nodePath: /srv/data
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

