---
keys:
  - &roche age1fch4w0x0hjaug9uudjg64ugern2tckut50zc4x6wjm2u02qjau9s6zl8ft
  - &kiptum age1tuvtu8ymxymejqfpmk87s0wh6hg95jtnz0vm7dl3472mjg55yfpsrpk20d
  - &kipchoge age1x4cn6aakq8zcfjxux4gyvledwh06e7t7z2cm8hlxfmdghvyaevaqlv6xxa
  - &dauwalter age14ka8kepyz9fw848a2a8qc6cyelphnfcp9049yl930mrcvtmufdcqzgxtxt
creation_rules:
  - path_regex: secrets/roche/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *roche
  - path_regex: secrets/kiptum/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *roche
          - *kiptum
  - path_regex: secrets/kipchoge/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *roche
          - *kipchoge
  - path_regex: secrets/dauwalter/[^/]+.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *roche
          - *dauwalter
  - path_regex: secrets/shared/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *roche
          - *kipchoge
          - *kiptum
