keys:
  - &roche CB28EBC0DBFF630B85BE20E0807ACF787AC92BEE
creation_rules:
  - path_regex: secrets/roche/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *roche
  - path_regex: secrets/kiptum/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *roche
  - path_regex: secrets/kipchoge/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *roche
