apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-rwx-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
