{
  imports = [
    ./boot.nix
    ./console.nix
    ./environment.nix
    ./i18n.nix
    ./networking.nix
    ./nix.nix
    ./portal.nix
    ./qt.nix
    ./security.nix
    ./ssh.nix
    ./sops.nix
    ./system.nix
    ./systemd.nix
    ./time.nix
    ./virtualisation.nix
  ];
}
