apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/rochecompaan/nixdots.git
    targetRevision: main
    path: argocd/homelab/nextcloud-db
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
