apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 8.7.0
    helm:
      releaseName: nextcloud
      valuesObject:
        internalDatabase:
          enabled: false
        externalDatabase:
          enabled: true
          type: postgresql
          host: postgres-rw
          database: nextcloud
          existingSecret:
            enabled: true
            secretName: postgres-app
            usernameKey: username
            passwordKey: password
        nextcloud:
          host: nextcloud.compaan
          trustedDomains:
            - nextcloud.compaan
          configs:
            proxy.config.php: |-
              <?php
              $CONFIG = array (
                'overwriteprotocol' => 'https',
                'overwritehost' => 'nextcloud.compaan',
                'overwrite.cli.url' => 'https://nextcloud.compaan',
                'trusted_proxies' =>
                array (
                  0 => '10.0.0.0/8',
                  1 => '172.16.0.0/12',
                  2 => '192.168.0.0/16',
                ),
              );
          existingSecret:
            enabled: true
            secretName: nextcloud-admin
            usernameKey: nextcloud-username
            passwordKey: nextcloud-password
          extraEnv:
            - name: APACHE_SERVER_NAME
              value: nextcloud.compaan
            - name: OVERWRITEPROTOCOL
              value: https
            - name: OVERWRITECLIURL
              value: https://nextcloud.compaan
          objectStore:
            s3:
              enabled: true
              host: garage.garage.svc.cluster.local
              ssl: false
              port: "3900"
              region: garage
              bucket: nextcloud-bucket
              usePathStyle: true
              existingSecret: nextcloud-s3
              secretKeys:
                host: host
                accessKey: accessKey
                secretKey: secretKey
                bucket: bucket
        persistence:
          enabled: true
          storageClass: longhorn
          size: 10Gi
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: compaan-ca
          tls:
            - secretName: nextcloud-compaan-tls
              hosts:
                - nextcloud.compaan
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
