---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webmutt-gmail-secret
  namespace: webmutt
spec:
  encryptedData:
    GMAIL_ADDRESS: AgBlcqzyDA+jutAhFRgLGGVWzyObtsOXm2L7ZHbDvLoSCf2a2uO2oeXB8ePtqvVoMtpyFZrnmEmGXA1irgAzWf9bixwahch1dVFvcJXeI/hEHe8dJODgMlBk2v+a4ct479g3lO6e7gKFus6AqfLGpK0ax4ngDCAUceGQClxESL5P7MN9TrqWtXCh9mmBlUcbk9oOR0JKMfoxfV6yrU1nWdKPTTs52fvwG5+i+ju5r5qSTYRDTJBa3C50cJCXRBF+hwiJvUCMeEImYfP2TzG/7Ee6XAJFobc0wlLxTaKpBZecOvUka7/sbVjhb2+T+UMP6Vd4LOcV8Lfe9+FLBgyvTTSk7LsdABvN0iAQclctC+06UUDw/48ea27KR9Jd2Md0IixlmFV+u6C1OcgvCLkWu+6nqKurdSErVjdkRI2Jw/Fo0mpcyj1miaAkB7T+x9+2Exk96N4yPCZhnuVNVIV2GhTuQ+RXxM90EsflJsogAuOIi1zrrIKAPctLziBgiHQSvVEsjOc9KHFs00XF+Q/iHzGqnEp/46JHlgiDgzG3OsBd0u0dJXpcpzLzTWeImc0n6fdpLbpyrOjwefQa2EOsS2rj55YyGpTLKumqRAVlHxTsBlsA5ZBsSFyzwWeZyL9ZI8X/5TrGn3+z21GWnVu2U+/8Ec4LRtF+62bAw30X4bh4LHo4ZsFN/jSzktK2YcBj+tQcerqiGNJJ6Lg11HipB/b0nxFMOhy6q+7Nq0E=
    GMAIL_APP_PASSWORD: AgBveNmjpjf56K2SucB/Wju+MTRDZfvbOGqUSUGI/maDysZOMxCj5l1z+JviDIZXRruT0DgLWI7J/SN+QJcmvXvijtLXtfy2H2SALI0amfGUqs5Tx4UyRHOaDv9raupMQiMNc6U8UITIaO42up6w/nePepLoaxEdukCNXoRflHAEU1NdTbndxOHVuh8zCqRb8owlUzwHqO1gmImtGrfwj9fPWWPXqeFUXYN3mMvJtboIULWL67GWt5mp4AjVYsLLt7RjwflZo/+hsv/2xk9VmoIwY95FgLebM2rcqAeEa0iJk9BFvCctGHl6KttYDL1m6J4sqXr1TxGk3yHuigZH9DSH+kg2wP5mRb7lyF5/uIXnx1VVO3UEgCcQOHsnOQFBY3sV3yO6apN3xy+tSVR5Hk3l7ZDQq/SfHUyCxuzGLs11VEgmTPPqUNXdoRl5lCCHLIWhZ76ZyE109JHjfGHssP6l2APgrbq4gJ6leSd1vNae8AFLs8Nzpk633EnguQDnVho3d3nYG1lP/xp4zrll7Mh9IkyrjJAdLUh8DjjVleUF3+ZfPQQBpRQi3oYftTXNJI//xBfAh5y8B5sk+AI1/hoUq8hDdvqI3Anm5r5qmPG/dcPQbqDsld4FalkHM281NhI5X7i6y6pBb5H/D6IkP1Nipie2UoX0/995ngvP+IDydaGxlVBwOdylo8Z6gGoVEqA4Q95lbFg+rstEl1A=
  template:
    metadata:
      name: webmutt-gmail-secret
      namespace: webmutt
