---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webmutt-gmail-secret
  namespace: webmutt
spec:
  encryptedData:
    GMAIL_ADDRESS: AgCwb9LVqDmWzeBoTENgYh9o2RY2wZzz5jMJ+HkS0Xfz7Snn8DLvEaXo2P0A02Be9mk98ryQ31Y3C5/UoPlbxc6gB0dWc+ZSUWM4nhvRv7DSH/yYhXekU51dzbgfrl6nUzMHjMjWuOMhBEfe3ZkwgwSjPWw+NiONDC53Ohgba2n3R8iExwxoGByrpAvlg7E2GCt4vpdINtio6hXhPii0Jn7zZWdEo4TAx3pknNgAz45118JD1AxOoF5D/7j6Rq6raZSYrKcwG5sQjoutk8zqVUyRH5Wbe3XzMAkjqQVzehnMAD4AR9kb3BY6Qy2WNn4cO5N4TTui5U0n3+oIgxWMdF4wicITUqn97bxi/lciPW1BK5qsiZRNb6M4sHSEFhNZvi5dkUnN5X8sT1gp2jTSurgM3qX8WPK4ELZYtrbQrSrtcK6wwVNd9MiQWjrZiyUDPU9Wa2oiw90GxjuCQm5z/HYXhdHdPqkR1W/nGeiVoxldczLLJyPju481D7jIIYZP3y18R0Df6NRFgQj6pM0vvLRA2QKdR27eBQlyGh/fzThXh5nvqEJnBEV8Q+vUS+t21yHel4zFqEpeHHgCJ5wxYVyDkwzqhcNDVMUNCzN8BYzSMvKASqs6nUae5hMSDtud8jJ4uEva7PTKLexyGeFwrFOAS6nXrxbdXLydAs+NG/X4xwx0FlqjmT5dkl74PsHi7DDfElFoTf6fJBBIsEBPfX2eOmFJRuyENFu5D7M=
    GMAIL_APP_PASSWORD: AgAb7Nh1vUqDhWtXBxQ5WsN3WGm3QlKU8LijySXh3Iw81tXyH3S4OMi+DTMDF5qPIIKbpaBhgPGya7H6fPRryK0su7NSawgCZM6JQH3boZ+PavyzIorGTNA8KTEXjZhfF4OS+O6Er5D8ygX2fEVY2Cj36UUzHhoEHZeZFa7VEmpNlClXbRohdVAjGjGu7vdSxc94pMO3fhANCAr1NUUBaGH+B48g1cZH5zchs7db667isJIuBq6oRFlbIgcrkCVAv1zwugFcRrckWOvBLkOv5KQmursNVwYgNHrjegkIaq3BT/vZOaKlfzELNHJ7h9JACadDj+ryD5NFfzEPybW8MgqD3HsGxxO4tnr1vYttqoCxCKr79RX/BiAW8jq0HvNOcdZSm/l1R2kL6yO7UAArtdabY57iMm4FlaVeck1gp+Pk40LgOPxDZ96m/gZehkyU04+kxniCvHf3Qso4RrSTjRxHrg8CpiaxxnyvcHBbV/c4IQ8uvDpJ5fjKAKinmdl994meKWUvUae+hoXK11wovOHXmc/J1J/9r81mRESgo4UbLHDdL28S7an+GVdkwFC0wZF1xPSKaiMZNLGrRliHuvAPVBP77t3WjxZCaQ9YpBQQJ/kwNFKOUv70YtjkJi4xZNGx/dRddVSBIuMdi8+Lfl+G0Z6rhHSSLavRPq+bTTmAd5LisrnlXZUNclYmcwwSgIX5VDaoAMhhLS+DqOOO22MY
  template:
    metadata:
      name: webmutt-gmail-secret
      namespace: webmutt
