apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  storage:
    size: 50Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
