{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkIf;
in
{
  config = mkIf config.default.isDesktop {
    home.packages = with pkgs; [
      android-tools
      copier
      devenv
      gimp
      keymapp
      libreoffice
      nextcloud-client
      obs-studio
      platformio
      playwright-test
      playwright-mcp
      qbittorrent-cli
      qbittorrent-enhanced
      scrcpy
      signal-desktop
      spacedrive
      ssh-to-age
      tea
      timewarrior
      transmission_4
      vesktop
      vlc
      wdisplays
      wlprop
      xprop
      yazi
      ydotool
    ];
  };
}
