apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ziti.server: |
    compaan:53 {
        errors
        cache 30
        forward . 192.168.1.100:1053 192.168.1.101:1053 192.168.1.102:1053 192.168.1.103:1053
    }
