{
  config,
  inputs,
  pkgs,
  ...
}:
{
  home = {
    username = "roche";
    homeDirectory = "/home/roche";
    stateVersion = "24.05";
    file.".local/share/fonts".source = ./fonts;
    activation = {
      installConfig = ''
        if [ ! -d "${config.home.homeDirectory}/.config/zsh" ]; then
          ${pkgs.git}/bin/git clone --depth 1 --branch zsh https://github.com/elythh/dotfiles ${config.home.homeDirectory}/.config/zsh
        fi
      '';
    };

    packages = with pkgs; [
      inputs.zjstatus.packages.${system}.default
      _1password-cli
      _1password-gui
      awscli
      bemoji
      bore-cli
      bruno
      charm
      charm-freeze
      chatterino2
      chromium
      circumflex
      clipse
      codespell
      colordiff
      copyq
      deadnix
      delta
      docker-compose
      eza
      feh
      fx
      fzf
      gcc
      gh
      git-absorb
      git-lfs
      gitmoji-cli
      glab
      glow
      gnumake
      go
      google-cloud-sdk
      go-task
      grimblast
      gum
      helmfile
      hclfmt
      hypnotix
      imagemagick
      inotify-tools
      jaq
      jq
      jqp
      just
      k8sgpt
      k9s
      keybase
      kubecolor
      kubectl
      kubectx
      kubeseal
      kubernetes-helm
      lapce
      light
      magic-wormhole
      marksman
      mods
      neovide
      networkmanagerapplet
      rofi-network-manager
      neovim-remote
      nix-fast-build
      nix-inspect
      nix-output-monitor
      nix-update
      nixfmt-rfc-style
      obsidian
      onefetch
      openssl
      openvpn
      oras
      pavucontrol
      pfetch
      picom
      pinentry-gtk2
      playerctl
      pre-commit
      presenterm
      qalculate-gtk
      qutebrowser
      rcon
      rustup
      satty
      sherlock
      skim
      skopeo
      slides
      sops
      starship
      stern
      syncthing
      swappy
      t-rec
      tailspin
      teleport
      tldr
      tuba
      update-nix-fetchgit
      vhs
      viddy
      wireplumber
      xdotool
      xwayland
      yarn
      yamlfmt
      yamllint
      zellij
      zoxide
    ];
  };
}
