---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webmutt-gmail-secret
  namespace: openclaw
spec:
  encryptedData:
    GMAIL_ADDRESS: AgB7DNmOHpO4L1nX6Snl7Im3zPcO+SemzA2HEqpkX+OTFyJZJSowXXJpBR0iHqMu5V+wyeF+di4bldcm+nR9zUpSIPFWO0lHXC2+WSahsvdQlEejeGMAa7N/PlDSMYynw835WbG+pYPHC7Bj8oBUiLUSsmPvsmLii3uPxF+CgEvtK8Bca8vbFQTfQif2gyqaMSwSlrZXPlawUozdXECsxjoTbKh6C4g3IRpqzO4CdCwIwxx26HtKtDTsEYhaHnZReMNz3d8kBqF0PUKDT0X2jTQcAyYdS0zJpGzvcZEmNzGPzYivJiqAK5onw+3aiAh2x+tYyuPUmTLJHhwahLGZfb7g1m43NF/kUsAEY3QWsW9XWrW7aJpyv0qjI4tNjkLiRwXDq8Z9MMSeeVU2MNk7gTGQXpZ0LlwcCRfwrSc7Xeg3HNbLZvLNug5qPFCcCtYNsDRKBuJZVdXv/LGk5vhUtO9Ha8Ree+oklok2bhCwEPP4qUuG9zwL86hrcK9BoD5T8a3jUDp1mFaBPD128BEoFeeS1q3p4y96offxlO37LIFs4+ujFx4ubwH3GDPCpwg/qz6PdWDre0mE4sGE3fPNVQxHF50cfo8EONTdrtd3WUqb8CAXLwl9CjXJg5+0METlXXUXBvC83qSapdOIyf53cOJSbzWgQsxKtjwGRUlyVMW0yDUZz2+vfEXdtLOlrNlrHrHmyaTYV7ZP4kkQFa8FtgTJSKkKBy5T0lWKd0k=
    GMAIL_APP_PASSWORD: AgCyAQ+cpSHZitvUbnQz+FjJSGXQUDKOuHXQ6+U59oi1R69GgXG0D4Yj+lJmyOxAno/1gJLViAEVmdhNn4Gk/KAy/ykV/mIitqgWTKlLV6PhDXfyXz4sZ4V8i5tzyDhysZYWIajiZbw/QqXkZeKw68tcYwj9WoKUf5g8+/NYe8QqFWMNnRvkBPsvqabC2KFrrIbud9MGWgSWv3bAJHt89qfjY5EDO5AAZi1bA5d3Nwl61uYY0NbVxhhoqij9/NFc2cwVooeLZGOdPz0gmfve/aUZzUHop2hf9UsRXyN+UEyvjA/vYdvBOC59UFZDQtSeL60fX3wNaRfozPZMcBsSDUFu6F9dEA4585bmtSFzx/zcCzx1rpScjtG5C8DYfKQHgDKjLcPYcwTL0PTpOMA+MFto3Rm/NMi3nE7dJfOC1FXaHQhk9Bys7q9EqvK8BCm+FF4N8+RWh8MlfJyweI2gZzEg1TUOO0ahVjLovsIHSibB3/daRx/zj+MY8t5GWDzcr3NfQ2zDmxH2NUv4XHS2hBqyOXWgYydNu6NXBXB3z9qQoSwAEpYV0VckejCn3ZXTmlXdoNUsPBDnWkso43ECwpCnGYO0VExf6AbuAwmGRLVplHnbBYcvhrxahUlIFqLZGorEDE1LCcvwmFT21rZI+66C3PYcT+Z/YuCYvuN4fCXxgY92d2lfvEI9r5ULa44Rw4ecxtIpbUU36/UXmx4g5ak3
  template:
    metadata:
      name: webmutt-gmail-secret
      namespace: openclaw
