---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webmutt-gmail-secret
  namespace: openclaw
spec:
  encryptedData:
    GMAIL_ADDRESS: AgBQ8M4F8I5MmY1157bS8JUbEcyjd+2ZISnlxuqLmof0bDYZv3byHVykXQJsPC6Y3lA9k7mAZiEcrk4sJ0iRjEuCT89BFqwbomTFSJVbLjhdOncqMtkDo3Af4IFnY6Ig4/yMgOPBNRjE5DCoK1VwLpFQ+TpCiL3qNALlHShidRFd5AZl4BdpeUKoR8ipwpW1ffq9pz9bOP06W4k+2irSdeyRiZrVPemMdDH/53avlaND+9t3k6E0KS6eRhR84pAvVCpRpbPJa4kDItpB9eTdgg3NRf/YMokg7pB8tOkuNthMp+aRyOqb7HR7NnO3jf+tYE+5lqYMzMiv/WGDiOIQUizVSkwYzGV1egEOnG0SJdunjDYnXNv4J4uuL87+Kvp9xXv/LiZH/4At6quZ9jNf9pOgWM1I1LeKQFf1zohaO99Gw7m+INMALtMpL0FkcxDqaZH6lUHI5FW2C69OJeNp6AXn1IB6IyukDtTz0IBvcZdByw2jEPGnOnY6Z6lCEymFIOvtRvHux95QRF3J8IfOtrlDfUhbbHWfbRbynfLsKbOd9SGIC0N1wBmNNXv/q5eSMZvh3bRl3wUEuaOZwDv+pj/4ES/qm5dRiPDtZirO1L/oTgMEJY8E/Q0UUoiAxC1gOP/3Jrlhr8Gp5Gic5JEuCqSEBxO2LRsX9dz8c7FkCR8ORIqAHcYui9acGLifjmUefKrBQW94Xxd89eznaWlZwvsJ1J3ofsIMFakYjZM=
    GMAIL_APP_PASSWORD: AgAFE+mWwxuC7/l5XWStuP+VHu2ne9jptg9LFLaJGpSP2RQsp4rgrcdYbnOHq0+6PzxPyj0qOymHavu9aPtJBf3q3wuuFtsgSmHPHMbZ3xXT/hNKripihGdm/tA1G55C27rpdMANVfVqNRt439rC6zoq7vINy56st6+7plaLW+iNjzKrx8jtbTXaEqAy9HWmTn6OLQnlmz+PuDXPV0vYTkSv2S07L77ghIJDdls/rsSIbhak3RBEHa4ieWdM5/bH7Y7VmU9su3tN9LwHEjMAw6UR5PnYlYJw21ukRV73F0LzOD3PsGOnVKumWaoubO2zeIaIid7FTO/D8QDQCw6BRwzqv0jKhO8y7BGUzqYXZoUYmBpSLGAz8B5mAPBbHqKkV5wSSYtGmchotVLGEw2ZKRY3HYzxnzXriEEG8xbrA5IG0Xvp0Xsi+2Md33j8ynqIkoB8aHG32I9w/wVYupjaH0LeF7ESZ0UQa7YiWJytk0AWgpnHM0+q7/mFnDWxJ3aubv7wd3fwbKg0e54iIZNd27nH/4E09N3EbOXCbtUCs6erp2J1Jhb5Ih0x2BpjcamlsURqiJ7I6GHUB8s5V9DOkxpv7iPfsQ2Kyaxr8SlT72MiyLR5zY5+NChp0G7QdNJGCvhZ08SepbkITjop/TJHB3uZtSp26YpCFG5i2c+PdWCtN1Xu7KgY7+Y+j8sizD47MMch+HXFhqNdf1TjuUw=
  template:
    metadata:
      name: webmutt-gmail-secret
      namespace: openclaw
